# Supabase CLI configuration for AI Tech News Assistant demo
# Replace "your-project-ref" with your actual Supabase project ref (e.g., xyzcompany-abcd1234)
project_id = "your-project-ref"
api_version = "2024-06-06"

[functions]
  [functions.semantic-search]
    verify_jwt = true
  [functions.ingest-article]
    verify_jwt = true
