/**
 * SuggestedQueries — M3.M2 chip row.
 *
 * Two callsites:
 *   1. Empty Research-tab state — 4-6 curated queries hardcoded by the
 *      parent.
 *   2. After a completed research report — 3 follow-up suggestions
 *      generated by a template extractor (M5 will upgrade to LLM).
 *
 * Click a chip → `onSelect(query)` fires. The parent decides what to do
 * (fill input + submit, in our case).
 *
 * Iter 2 fix — chips are real `<button type="button">` elements, not
 * `<Badge>` (which renders a `<div>`). Buttons are keyboard-focusable,
 * support Enter/Space activation, and pass the Playwright a11y check
 * `followUps.locator("button").count() > 0`.
 *
 * M3.M6 — chips stagger in on mount via framer-motion (30ms between
 * children, ~200ms total). Honors `prefers-reduced-motion`: when the OS
 * reports reduced motion, the transition resolves instantly.
 */

import { motion, useReducedMotion } from "framer-motion";

interface SuggestedQueriesProps {
  queries: string[];
  onSelect: (query: string) => void;
  /**
   * Optional label rendered above the chip row. Defaults to empty
   * (parent supplies its own header). The Research-tab empty state
   * uses this for "Suggested queries:" / "Try a follow-up question:".
   */
  label?: string;
  /**
   * Testid for the chip row container. Distinct between callsites so
   * Playwright can target the empty-state row vs the follow-up row.
   */
  "data-testid"?: string;
  /**
   * Per-chip testid. Defaults to "suggested-query-chip" (back-compat
   * with the empty-state callsite). The follow-up callsite passes
   * "research-follow-up-chip" so tests can target the two rows
   * independently.
   */
  chipTestId?: string;
}

export function SuggestedQueries({
  queries,
  onSelect,
  label,
  "data-testid": testid,
  chipTestId = "suggested-query-chip",
}: SuggestedQueriesProps): JSX.Element | null {
  const reduceMotion = useReducedMotion();
  if (!queries || queries.length === 0) return null;

  // Per-chip stagger via a parent container that schedules child
  // animations 30ms apart. When the OS reports reduced motion, the
  // transition resolves instantly (no stagger, no slide) so the
  // accessibility contract holds.
  const containerVariants = {
    hidden: { opacity: 1 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: reduceMotion ? 0 : 0.03,
        delayChildren: 0,
      },
    },
  } as const;
  const chipVariants = {
    hidden: reduceMotion
      ? { opacity: 1, y: 0 }
      : { opacity: 0, y: 4 },
    visible: {
      opacity: 1,
      y: 0,
      transition: {
        duration: reduceMotion ? 0 : 0.18,
        ease: "easeOut" as const,
      },
    },
  } as const;

  return (
    <div data-testid={testid}>
      {label && (
        <p className="text-sm text-muted-foreground mb-2">
          {label}
        </p>
      )}
      <motion.div
        className="flex flex-wrap gap-2"
        variants={containerVariants}
        initial="hidden"
        animate="visible"
      >
        {queries.map((q, idx) => (
          <motion.button
            key={`${idx}-${q.slice(0, 16)}`}
            type="button"
            data-testid={chipTestId}
            onClick={() => onSelect(q)}
            variants={chipVariants}
            className="inline-flex items-center rounded-md border border-border bg-transparent px-2.5 py-0.5 text-xs font-semibold text-foreground cursor-pointer hover:bg-accent hover:text-accent-foreground focus:outline-none focus-visible:ring-2 focus-visible:ring-ring transition-colors"
          >
            {q}
          </motion.button>
        ))}
      </motion.div>
    </div>
  );
}

export default SuggestedQueries;
