/**
 * SuggestedQueries — M3.M2 chip row.
 *
 * Two callsites:
 *   1. Empty Research-tab state — 4-6 curated queries hardcoded by the
 *      parent.
 *   2. After a completed research report — 3 follow-up suggestions
 *      generated by a template extractor (M5 will upgrade to LLM).
 *
 * Click a chip → `onSelect(query)` fires. The parent decides what to do
 * (fill input + submit, in our case).
 *
 * Iter 2 fix — chips are real `<button type="button">` elements, not
 * `<Badge>` (which renders a `<div>`). Buttons are keyboard-focusable,
 * support Enter/Space activation, and pass the Playwright a11y check
 * `followUps.locator("button").count() > 0`.
 */

interface SuggestedQueriesProps {
  queries: string[];
  onSelect: (query: string) => void;
  /**
   * Optional label rendered above the chip row. Defaults to empty
   * (parent supplies its own header). The Research-tab empty state
   * uses this for "Suggested queries:" / "Try a follow-up question:".
   */
  label?: string;
  /**
   * Testid for the chip row container. Distinct between callsites so
   * Playwright can target the empty-state row vs the follow-up row.
   */
  "data-testid"?: string;
  /**
   * Per-chip testid. Defaults to "suggested-query-chip" (back-compat
   * with the empty-state callsite). The follow-up callsite passes
   * "research-follow-up-chip" so tests can target the two rows
   * independently.
   */
  chipTestId?: string;
}

export function SuggestedQueries({
  queries,
  onSelect,
  label,
  "data-testid": testid,
  chipTestId = "suggested-query-chip",
}: SuggestedQueriesProps): JSX.Element | null {
  if (!queries || queries.length === 0) return null;

  return (
    <div data-testid={testid}>
      {label && (
        <p className="text-sm text-gray-600 dark:text-gray-400 mb-2">
          {label}
        </p>
      )}
      <div className="flex flex-wrap gap-2">
        {queries.map((q, idx) => (
          <button
            key={`${idx}-${q.slice(0, 16)}`}
            type="button"
            data-testid={chipTestId}
            onClick={() => onSelect(q)}
            className="inline-flex items-center rounded-md border border-gray-300 dark:border-gray-700 bg-transparent px-2.5 py-0.5 text-xs font-semibold text-gray-800 dark:text-gray-200 cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 focus:outline-none focus-visible:ring-2 focus-visible:ring-blue-500 transition-colors"
          >
            {q}
          </button>
        ))}
      </div>
    </div>
  );
}

export default SuggestedQueries;
