import { Badge } from "./ui/badge";

/**
 * SuggestedQueries — M3.M2 chip row.
 *
 * Two callsites:
 *   1. Empty Research-tab state — 4-6 curated queries hardcoded by the
 *      parent.
 *   2. After a completed research report — 3 follow-up suggestions
 *      generated by a template extractor (M5 will upgrade to LLM).
 *
 * Click a chip → `onSelect(query)` fires. The parent decides what to do
 * (fill input + submit, in our case).
 */

interface SuggestedQueriesProps {
  queries: string[];
  onSelect: (query: string) => void;
  /**
   * Optional label rendered above the chip row. Defaults to empty
   * (parent supplies its own header). The Research-tab empty state
   * uses this for "Suggested queries:" / "Try a follow-up question:".
   */
  label?: string;
  /**
   * Testid for the chip row container. Distinct between callsites so
   * Playwright can target the empty-state row vs the follow-up row.
   */
  "data-testid"?: string;
}

export function SuggestedQueries({
  queries,
  onSelect,
  label,
  "data-testid": testid,
}: SuggestedQueriesProps): JSX.Element | null {
  if (!queries || queries.length === 0) return null;

  return (
    <div data-testid={testid}>
      {label && (
        <p className="text-sm text-gray-600 dark:text-gray-400 mb-2">
          {label}
        </p>
      )}
      <div className="flex flex-wrap gap-2">
        {queries.map((q, idx) => (
          <Badge
            key={`${idx}-${q.slice(0, 16)}`}
            variant="outline"
            data-testid="suggested-query-chip"
            className="cursor-pointer hover:bg-gray-100 dark:hover:bg-gray-800 transition-colors"
            onClick={() => onSelect(q)}
          >
            {q}
          </Badge>
        ))}
      </div>
    </div>
  );
}

export default SuggestedQueries;
