# Railway Deployment Configuration
# AI Tech News Assistant (Backend + Frontend)

[project]
name = "ai-tech-news-assistant"

[[services]]
name = "backend"
source = "backend"
buildCommand = "pip install --upgrade pip && pip install -r requirements.txt"
startCommand = "uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2"

	[services.env]
	ENVIRONMENT = "production"
	DEBUG = "false"
	CORS_ORIGINS = "https://your-frontend-domain.vercel.app"
		# Set OPENAI_API_KEY and DATABASE_URL in the Railway dashboard.

[[services]]
name = "frontend"
source = "frontend"
buildCommand = "npm install && npm run build"
startCommand = "npx serve -s dist -l $PORT"

	[services.env]
	NODE_ENV = "production"
	VITE_API_BASE_URL = "{{ services.backend.url }}"

[[services]]
name = "redis"
image = "redis:7-alpine"
startCommand = "redis-server --appendonly yes"
