services:
  - type: web
    name: ai-tech-news-backend
    env: python
    rootDir: backend
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT --workers 2
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: DEBUG
        value: "false"
      - key: CORS_ORIGINS
        value: https://your-frontend-domain.vercel.app
      - key: OPENAI_API_KEY
        sync: false
      - key: DATABASE_TYPE
        value: postgresql
      - key: DATABASE_URL
        sync: false
        # On Render dashboard, set this to your PostgreSQL connection string:
        # postgresql://user:password@host:5432/database

  - type: web
    name: ai-tech-news-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    autoDeploy: true
    envVars:
      - key: VITE_API_BASE_URL
        fromService:
          name: ai-tech-news-backend
          type: web
          property: url
