"""Create initial database schema

Revision ID: 001
Revises: 
Create Date: 2024-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create users table
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('hashed_password', sa.String(length=255), nullable=False),
        sa.Column('full_name', sa.String(length=100), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('last_login', sa.DateTime(), nullable=True),
        sa.Column('preferences', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_users_active', 'users', ['is_active'], unique=False)
    op.create_index('idx_users_email', 'users', ['email'], unique=False)
    op.create_index('idx_users_username', 'users', ['username'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    
    # Create sources table
    op.create_table('sources',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('url', sa.String(length=500), nullable=False),
        sa.Column('rss_url', sa.String(length=500), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('scrape_frequency', sa.Integer(), nullable=False),
        sa.Column('last_scraped', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('metadata', sa.VARCHAR(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('url')
    )
    op.create_index('idx_sources_active', 'sources', ['is_active'], unique=False)
    op.create_index('idx_sources_last_scraped', 'sources', ['last_scraped'], unique=False)
    op.create_index('idx_sources_name', 'sources', ['name'], unique=False)
    op.create_index(op.f('ix_sources_id'), 'sources', ['id'], unique=False)
    
    # Create categories table
    op.create_table('categories',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('slug', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('color', sa.String(length=7), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('slug')
    )
    op.create_index('idx_categories_active', 'categories', ['is_active'], unique=False)
    op.create_index('idx_categories_name', 'categories', ['name'], unique=False)
    op.create_index('idx_categories_slug', 'categories', ['slug'], unique=False)
    op.create_index(op.f('ix_categories_id'), 'categories', ['id'], unique=False)
    
    # Create articles table
    op.create_table('articles',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=500), nullable=False),
        sa.Column('url', sa.String(length=1000), nullable=False),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('summary', sa.Text(), nullable=True),
        sa.Column('author', sa.String(length=200), nullable=True),
        sa.Column('published_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.Column('language', sa.String(length=10), nullable=True),
        sa.Column('word_count', sa.Integer(), nullable=True),
        sa.Column('reading_time', sa.Integer(), nullable=True),
        sa.Column('is_archived', sa.Boolean(), nullable=False),
        sa.Column('is_featured', sa.Boolean(), nullable=False),
        sa.Column('view_count', sa.Integer(), nullable=False),
        sa.Column('sentiment_score', sa.Float(), nullable=True),
        sa.Column('embedding_generated', sa.Boolean(), nullable=False),
        sa.Column('summary_generated', sa.Boolean(), nullable=False),
        sa.Column('source_id', sa.Integer(), nullable=True),
        sa.Column('metadata', sa.VARCHAR(), nullable=True),
        sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('url')
    )
    op.create_index('idx_articles_archived', 'articles', ['is_archived'], unique=False)
    op.create_index('idx_articles_compound_processing', 'articles', ['embedding_generated', 'summary_generated'], unique=False)
    op.create_index('idx_articles_compound_status', 'articles', ['is_archived', 'is_featured'], unique=False)
    op.create_index('idx_articles_created_at', 'articles', ['created_at'], unique=False)
    op.create_index('idx_articles_embedding_generated', 'articles', ['embedding_generated'], unique=False)
    op.create_index('idx_articles_featured', 'articles', ['is_featured'], unique=False)
    op.create_index('idx_articles_published_at', 'articles', ['published_at'], unique=False)
    op.create_index('idx_articles_source_id', 'articles', ['source_id'], unique=False)
    op.create_index('idx_articles_summary_generated', 'articles', ['summary_generated'], unique=False)
    op.create_index('idx_articles_title', 'articles', ['title'], unique=False)
    op.create_index('idx_articles_url', 'articles', ['url'], unique=False)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    
    # Create embeddings table
    op.create_table('embeddings',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('article_id', sa.Integer(), nullable=False),
        sa.Column('embedding_vector', sa.Text(), nullable=False),
        sa.Column('embedding_model', sa.String(length=100), nullable=False),
        sa.Column('embedding_dim', sa.Integer(), nullable=False),
        sa.Column('content_type', sa.String(length=50), nullable=False),
        sa.Column('chunk_index', sa.Integer(), nullable=True),
        sa.Column('chunk_text', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('processing_time', sa.Float(), nullable=True),
        sa.Column('model_version', sa.String(length=50), nullable=True),
        sa.Column('metadata', sa.VARCHAR(), nullable=True),
        sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('article_id', 'content_type', 'embedding_model', 'chunk_index', name='uq_embeddings_article_content_model_chunk')
    )
    op.create_index('idx_embeddings_article_id', 'embeddings', ['article_id'], unique=False)
    op.create_index('idx_embeddings_compound', 'embeddings', ['article_id', 'content_type', 'embedding_model'], unique=False)
    op.create_index('idx_embeddings_content_type', 'embeddings', ['content_type'], unique=False)
    op.create_index('idx_embeddings_model', 'embeddings', ['embedding_model'], unique=False)
    op.create_index(op.f('ix_embeddings_id'), 'embeddings', ['id'], unique=False)
    
    # Create association table for article-category many-to-many relationship
    op.create_table('article_categories',
        sa.Column('article_id', sa.Integer(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
        sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
        sa.PrimaryKeyConstraint('article_id', 'category_id')
    )
    op.create_index('idx_article_category_article', 'article_categories', ['article_id'], unique=False)
    op.create_index('idx_article_category_category', 'article_categories', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_article_category_category', table_name='article_categories')
    op.drop_index('idx_article_category_article', table_name='article_categories')
    op.drop_table('article_categories')
    op.drop_index(op.f('ix_embeddings_id'), table_name='embeddings')
    op.drop_index('idx_embeddings_model', table_name='embeddings')
    op.drop_index('idx_embeddings_content_type', table_name='embeddings')
    op.drop_index('idx_embeddings_compound', table_name='embeddings')
    op.drop_index('idx_embeddings_article_id', table_name='embeddings')
    op.drop_table('embeddings')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_index('idx_articles_url', table_name='articles')
    op.drop_index('idx_articles_title', table_name='articles')
    op.drop_index('idx_articles_summary_generated', table_name='articles')
    op.drop_index('idx_articles_source_id', table_name='articles')
    op.drop_index('idx_articles_published_at', table_name='articles')
    op.drop_index('idx_articles_featured', table_name='articles')
    op.drop_index('idx_articles_embedding_generated', table_name='articles')
    op.drop_index('idx_articles_created_at', table_name='articles')
    op.drop_index('idx_articles_compound_status', table_name='articles')
    op.drop_index('idx_articles_compound_processing', table_name='articles')
    op.drop_index('idx_articles_archived', table_name='articles')
    op.drop_table('articles')
    op.drop_index(op.f('ix_categories_id'), table_name='categories')
    op.drop_index('idx_categories_slug', table_name='categories')
    op.drop_index('idx_categories_name', table_name='categories')
    op.drop_index('idx_categories_active', table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_sources_id'), table_name='sources')
    op.drop_index('idx_sources_name', table_name='sources')
    op.drop_index('idx_sources_last_scraped', table_name='sources')
    op.drop_index('idx_sources_active', table_name='sources')
    op.drop_table('sources')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index('idx_users_username', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_index('idx_users_active', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
