name: CI - Build and Test

on:
  push:
    branches: [ main, feature/* ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  # Build and test both backend and frontend
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
        
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: frontend/package-lock.json
    
    - name: Install Python dependencies
      run: |
        cd backend
        pip install -r requirements.txt
        
    - name: Install Node dependencies
      run: |
        cd frontend
        # Solution from https://github.com/npm/cli/issues/4828
        # Delete both package-lock.json and node_modules to generate complete cross-platform lockfile
        rm -rf node_modules package-lock.json
        # Install fresh to get all platform dependencies in lockfile
        npm install
        # Run npm update to ensure all optional deps are properly resolved
        npm update
        
    - name: Run backend tests
      run: |
        # Test basic backend functionality
        cd backend
        python -c "
        try:
            import simple_main
            print('✓ Backend imports successfully')
            from simple_main import app
            print('✓ FastAPI app created successfully')
        except Exception as e:
            print(f'❌ Backend test failed: {e}')
            exit(1)
        "
        
        # Run CI-friendly tests if available
        cd ..
        if [ -f "tests/test_ci_simple.py" ]; then
            echo "Running validation tests..."
            python tests/test_ci_simple.py
        else
            echo "✓ Basic backend validation completed"
        fi
        
    - name: Build frontend
      run: |
        cd frontend
        # Build with clean dependencies (npm update should have resolved platform issues)
        npm run build:ci
        
    - name: Test Summary
      run: |
        echo "✅ Build and Test Summary:"
        echo "✓ Backend imports and validation: PASSED"
        echo "✓ Frontend build: PASSED"
        echo "✓ All tests completed successfully!"

  # Optional: Basic security scan (only on main branch)
  security-scan:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
    - uses: actions/checkout@v4
    
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'table'
        exit-code: '0'  # Don't fail build on vulnerabilities
